apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: onenet
  name: hlfcli
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hlfcli
    spec:
     
      containers:
      - name: hlfcli
        image: hyperledger/fabric-tools:x86_64-1.0.0
        env:
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: GOPATH
            value: /opt/gopath
          - name: CORE_LOGGING_LEVEL
            value: DEBUG
          - name: CORE_PEER_ID
            value: cli
        command: ["sh","-c","sleep 9999999"]
        volumeMounts:
            - mountPath: /opt/ws/
              name: nfs
              subPath: ws
            - mountPath: /opt/gopath/src
              name: nfs
              subPath: ws/chaincode/  

      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName:  shared-data
