apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: onenet
  name: shared-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 99Mi