apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: onenet
  name: nfs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.7.248.213
    path: "/"