apiVersion: v1
kind: Service
metadata:
   namespace: onenet
   name: peer0
   labels:
    app: peer0
spec:
   ports:
      - name: externale-listen-endpoint
        protocol: TCP
        port: 7051
        targetPort: 7051
      - name: chaincode-listen
        protocol: TCP
        port: 7052
        targetPort: 7052
      - name: event-listen
        protocol: TCP
        port: 7053
        targetPort: 7053 
   selector:
        run: peer0  

---